name: CD - Terraform + ECS Blue Green Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3Ô∏è‚É£ Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      # 4Ô∏è‚É£ Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      # 5Ô∏è‚É£ Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve -input=false \
            -var="ecr_image_uri=301782007642.dkr.ecr.ap-south-1.amazonaws.com/paktha-strapi-ecs:latest"
      - name: Checkout repository
        uses: actions/checkout@v4

      # 6Ô∏è‚É£ Render task definition
      - name: Render ECS task definition
        run: |
          cp taskdef-template.json taskdef.json
      
          sed -i "s|<IMAGE_URI>|${{ env.ECR_IMAGE }}|g" taskdef.json
          sed -i "s|<APP_KEYS>|${{ secrets.APP_KEYS }}|g" taskdef.json
          sed -i "s|<API_TOKEN_SALT>|${{ secrets.API_TOKEN_SALT }}|g" taskdef.json
          sed -i "s|<ADMIN_JWT_SECRET>|${{ secrets.ADMIN_JWT_SECRET }}|g" taskdef.json
          sed -i "s|<JWT_SECRET>|${{ secrets.JWT_SECRET }}|g" taskdef.json
      

      # 7Ô∏è‚É£ üöÄ DEPLOY (PASTE IT HERE)
      - name: Deploy to ECS using CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: taskdef.json
          service: paktha-strapi-service
          cluster: paktha-strapi-cluster
          codedeploy-appspec: appspec.yaml
          codedeploy-application: paktha-strapi-codedeploy
          codedeploy-deployment-group: paktha-strapi-dg


