name: CD - ECS Blue Green Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 1️⃣ Render task definition
      - name: Render task definition
        run: |
          sed "s|<IMAGE_URI>|301782007642.dkr.ecr.ap-south-1.amazonaws.com/paktha-strapi-ecs:latest|g" \
          app/taskdef-template.json > taskdef.json

      # 2️⃣ Register task definition and capture ARN
      - name: Register ECS task definition
        id: taskdef
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      # 3️⃣ Inject task definition ARN into AppSpec
      - name: Render AppSpec
        run: |
          sed "s|TASK_DEFINITION_ARN|${{ env.TASK_DEF_ARN }}|g" \
          appspec.yaml > appspec.rendered.yaml

      # 4️⃣ Create CodeDeploy deployment
      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name paktha-strapi-codedeploy \
            --deployment-group-name paktha-strapi-dg \
            --revision revisionType=AppSpecContent,appSpecContent="{\"content\":\"$(cat appspec.rendered.yaml | sed 's/\"/\\\\\"/g')\"}" \
            --region ap-south-1
