name: CD - ECS Blue Green Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false


      - name: Set ECR image URI
        run: |
          echo "ECR_IMAGE=301782007642.dkr.ecr.ap-south-1.amazonaws.com/paktha-strapi-ecs:${{ github.sha }}" >> $GITHUB_ENV

      - name: Render ECS task definition
        run: |
          export IMAGE_URI=${{ env.ECR_IMAGE }}
          export APP_KEYS="${{ secrets.APP_KEYS }}"
          export API_TOKEN_SALT="${{ secrets.API_TOKEN_SALT }}"
          export ADMIN_JWT_SECRET="${{ secrets.ADMIN_JWT_SECRET }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
      
          envsubst < taskdef-template.json > taskdef.json
      - name: Verify task definition
        run: |
          cat taskdef.json | grep image
      

      - name: Verify task definition image
        run: |
          echo "Rendered image:"
          grep '"image"' taskdef.json


      - name: Deploy to ECS using CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: taskdef.json
          service: paktha-strapi-service
          cluster: paktha-strapi-cluster
          codedeploy-appspec: appspec.yaml
          codedeploy-application: paktha-strapi-codedeploy
          codedeploy-deployment-group: paktha-strapi-dg
