name: CD - ECS Blue Green Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4

      # 2️⃣ AWS creds
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3️⃣ Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      # 4️⃣ Terraform Apply (THIS CREATES CODEDEPLOY APP)
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false

      # 5️⃣ Render task definition
      - name: Render task definition
        run: |
          sed "s|<IMAGE_URI>|301782007642.dkr.ecr.ap-south-1.amazonaws.com/paktha-strapi-ecs:latest|g" \
          app/taskdef-template.json > taskdef.json

      # 6️⃣ Register ECS task definition
      - name: Register ECS task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://taskdef.json

      # 7️⃣ Create CodeDeploy deployment
      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name paktha-strapi-codedeploy \
            --deployment-group-name paktha-strapi-dg \
            --revision file://appspec.json \
            --region ap-south-1
