name: CD - ECS Fargate Deploy

on:
  workflow_dispatch:
    inputs:
      image_uri:
        description: "ECR Image URI"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Verify AWS access
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
      - name: unlock state
        run: terraform force-unlock 40caea43-f1b4-227e-5717-30e58c0b706c
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
      

      - name: Terraform Init 
        working-directory: terraform
        run: terraform init -input=false -migrate-state
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1


      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -var="ecr_image_uri=301782007642.dkr.ecr.eu-north-1.amazonaws.com/paktha-strapi-ecs:latest" 
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
