name: Terraform State Fix (One Time)

on:
  workflow_dispatch:

jobs:
  state-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init (S3 backend)
        working-directory: terraform
        run: terraform init -input=false

      - name: Verify Backend Loaded
        working-directory: terraform
        run: terraform state list

      - name: REMOVE STALE SECURITY GROUPS FROM STATE
        working-directory: terraform
        run: |
          terraform state rm aws_security_group.ecs || true
          terraform state rm aws_security_group.alb || true
